# Copyright (c) 2025 Christophe Dufaza
# SPDX-License-Identifier: Apache-2.0

# See:
# - The mypy configuration file
#   https://mypy.readthedocs.io/en/stable/config_file.html

[mypy]
python_version = 3.10
mypy_path = src
packages = dtsh
# Work-around for mypy warnings "Skipping analyzing X: module is installed,
# but missing library stubs or py.typed marker", e.g. when importing
# the devicetree package.
# See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
ignore_untyped_imports = True
