# Copyright (c) 2025, Christophe Dufaza
# SPDX-License-Identifier: Apache-2.0

[build-system]
# setuptools: Support for project.license-files and SPDX license expressions
# in project.license (PEP 639) were introduced in version 77.0.0.
requires = ["setuptools>=77.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dtsh"
authors = [
  { name="Christophe Dufaza", email="chris@openmarl.org" },
]
description = "Devicetree Shell"
readme = "README.md"
# Zephyr minimal Python version.
requires-python = ">=3.10"
license = "Apache-2.0"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Embedded Systems",
]
keywords = [
    "Devicetree",
    "DTS",
    "Zephyr",
]

# For dynamic versions,
# see https://setuptools-scm.readthedocs.io/en/stable/usage/
# dynamic = [
#   "version",
# ]
# [tool.setuptools_scm.scm.git]
# branch = "zephyr"
#
# Would help with maintainance,
# but requires to add one more step to "build" the Zephyr module
# and generate the Python package's version meta-data.
# For now, track the Zephyr stable release we're developing and testing with.
version = "4.2.1"

# Run-time dependencies for "west dtsh",
# aka scripts/requirements.txt
dependencies = [
    "PyYAML>=6.0",  # Should already be installed with Zephyr Python requirements.
    "rich",
    "gnureadline; sys_platform == 'darwin'",

    # devicetree: We assume West command execution environment,
    # the devicetree package should always be imported
    # from $ZEPHYR_BASE/scripts/dts/python-devicetree/src
]

[project.urls]
Homepage =      "https://github.com/dottspina/dtsh"
Documentation = "https://dottspina.github.io/dtsh/handbook.html"
Issues =        "https://github.com/dottspina/dtsh/issues"

[project.scripts]
dtsh = "dtsh.cli:run"

[project.optional-dependencies]
dev = [
    # devicetree: Would install obsolete version 0.0.2, Apr, 2022.
    # see https://pypi.org/project/devicetree/#history
    # For development, install as local pip project instead:
    # pip install $ZEPHYR_BASE/scripts/dts/python-devicetree

    # Dependency of scripts/dtsh_cmd.py.
    # Keep the version identical to the minimum
    # required in zephyr/cmake/modules/west.cmake
    "west>=0.14.0",

    "ruff",

    "mypy",
    "types-PyYAML",

    "pytest",
]

[tool.setuptools]
include-package-data = true # Should be true by default.

[tool.setuptools.packages.find]
where = ["src"]
namespaces = false

[tool.pytest.ini_options]
pythonpath = [
    "src",
]
testpaths = [
    "tests",
]
