# Copyright (c) 2025, Christophe Dufaza
# SPDX-License-Identifier: Apache-2.0

# See:
# https://docs.astral.sh/ruff/configuration
# https://docs.astral.sh/ruff/settings

line-length = 100
indent-width = 4
target-version = "py310"
include = ["pyproject.toml", "src/**/*.py", "scripts/dtsh_cmd.py"]

[lint]
select = [
    "B",      # flake8-bugbear
    "E",      # pycodestyle
    "F",      # pyflakes
    "I",      # isort
    "SIM",    # flake8-simplify
    "UP",     # pyupgrade
    "W",      # pycodestyle warnings
]
# ignore = [
#     "SIM108", # Allow if-else blocks instead of forcing ternary operator
# ]

[lint.per-file-ignores]
"scripts/west_commands/dtsh_cmd.py" = [
    "E402",     # https://docs.astral.sh/ruff/rules/module-import-not-at-top-of-file/
]

[format]
quote-style = "preserve"
line-ending = "lf"
# exclude = ["path/to/foo.py", "path/to/bar.py", ]
